name: Variable Sky
lsi: false
pygments: true
github: https://github.com/wballard/VariableSky
plugins: _plugins
markdown: redcarpet
redcarpet:
  extensions: ["with_toc_data", "tables", "no_intra_emphasis", "fenced_code_blocks", "autolink", "strikethrough", "superscript", "with_toc_data", "highlight"]
